[build]
  publish = "dist"
  command = "npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/sanity-api/*"
  to = "https://j4xtzihv.api.sanity.io/:splat"
  status = 200
  force = true
